import Navbar from "@/_components/Navbar";
import Sidebar from "@/_components/Sidebar";
import SubredditsList from "@/_components/SubredditsList";
import "@/globals.css";
import Providers from "@/providers";

export const metadata = {
  title: "Reddit Mini",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-100 text-gray-900">
        <Providers>
          <Navbar />
          <main className="flex">
            <Sidebar
              position={"left"}
              sidebarWidth={"w-1/6"}
              subredditsList={<SubredditsList />}
              toggleButton={true}
              className="p-4"
            />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
