import Navbar from "@/_components/Navbar";
import Sidebar from "@/_components/Sidebar";
import SubredditsList from "@/_components/SubredditsList";
import "@/globals.css";
import Providers from "@/providers";

export const metadata = {
  title: "Reddit Mini",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-100 text-gray-900">
        <Providers>
          <main className="flex h-screen flex-col">
            <Navbar />
            <section className="flex flex-1">
              <Sidebar
                position={"left"}
                sidebarWidth={"2xl:w-1/7 md:w-2/7"}
                data={<SubredditsList />}
                toggleButton={true}
                className="p-4"
              />
              {children}
            </section>
          </main>
        </Providers>
      </body>
    </html>
  );
}
