import Navbar from "./_components/Navbar";
import "./globals.css";
import Providers from "./providers";

export const metadata = {
  title: "Reddit Mini",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-100 text-gray-900">
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
